services:
  backend:
    build: ./backend
    command: ["nodemon", "--legacy-watch", "src/index.js"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis

  worker:
    build: ./backend
    command: ["nodemon", "--legacy-watch", "src/worker.js"]
    depends_on:
      - backend
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0" # LATER RUN BUILD NOT DEV
  
volumes:
  mongodb_data: